-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('CREATE_TOKEN_REQUESTED', 'CREATE_TOKEN_SUCCEEDED', 'CREATE_TOKEN_FAILED', 'CREATE_UPLOAD_REQUEST_REQUESTED', 'CREATE_UPLOAD_REQUEST_SUCCEEDED', 'CREATE_UPLOAD_REQUEST_FAILED', 'UPLOAD_REQUESTED', 'UPLOAD_SUCCEEDED', 'UPLOAD_FAILED', 'ESTIMATES_REQUESTED', 'ESTIMATES_SUCCEEDED', 'ESTIMATES_FAILED', 'GET_PROFILE_REQUESTED', 'GET_PROFILE_SUCCEEDED', 'GET_PROFILE_FAILED', 'GENERATE_NONCE_REQUESTED', 'GENERATE_NONCE_SUCCEEDED', 'GENERATE_NONCE_FAILED', 'VERIFY_AUTH_REQUESTED', 'VERIFY_AUTH_SUCCEEDED', 'VERIFY_AUTH_FAILED', 'REFRESH_TOKEN_REQUESTED', 'REFRESH_TOKEN_SUCCEEDED', 'REFRESH_TOKEN_FAILED');

-- CreateTable
CREATE TABLE "FeeTransaction" (
    "id" TEXT NOT NULL,
    "amount" TEXT NOT NULL,
    "amountInSubUnits" TEXT NOT NULL,
    "status" "TransactionStatus" NOT NULL DEFAULT 'PENDING',
    "transactionHash" TEXT,
    "uploadId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeeTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Log" (
    "id" TEXT NOT NULL,
    "eventType" "EventType" NOT NULL,
    "message" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Log_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "FeeTransaction_transactionHash_key" ON "FeeTransaction"("transactionHash");

-- CreateIndex
CREATE UNIQUE INDEX "FeeTransaction_uploadId_key" ON "FeeTransaction"("uploadId");

-- AddForeignKey
ALTER TABLE "FeeTransaction" ADD CONSTRAINT "FeeTransaction_uploadId_fkey" FOREIGN KEY ("uploadId") REFERENCES "Upload"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
